import javax.swing.GroupLayout.Alignment;
import javax.swing.Icon;
import javax.imageio.ImageIO;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import javafx.scene.image.Image;

import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;


public class GagnePartie extends javax.swing.JFrame {

    /**
     * Creates new form FinPartie
     * @param text
     */
    public GagnePartie(String text,String text2) {
    	getContentPane().setFont(new Font("Skater Girls Rock", Font.ITALIC, 11));
    	getContentPane().setBackground(new Color(102, 205, 170));
        initComponents();
        
        lb2.setText(text);
        icon.setText(text2);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                              
    private void initComponents() {
        lb2 = new javax.swing.JLabel();
        lb2.setForeground(new Color(0, 255, 0));
        jButton1 = new javax.swing.JButton();
        jButton1.setBackground(new Color(102, 205, 170));
        jButton1.setFont(new Font("Skater Girls Rock", Font.ITALIC, 11));
        jButton2 = new javax.swing.JButton();
        jButton2.setBackground(new Color(102, 205, 170));
        jButton2.setFont(new Font("Skater Girls Rock", Font.ITALIC, 11));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        jButton1.setText("Rejouer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
                
            	//nbrcorsaire=	Integer.valueOf(nbrCorsaire.getText());
    			//nbrcase =	Integer.valueOf(nbCases.getText());
    			       LancerPartie lanc = null;
    			       lanc.nb=12;
    			       lanc=new LancerPartie();
    			        
    				//this.dispose();
            }
        });

        jButton2.setText("Quiter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        
        icon = new JLabel();
        icon.setText("<dynamic>");
        icon.setForeground(Color.GREEN);
        icon.setFont(new Font("Dialog", Font.PLAIN, 24));
        
        JButton btnSavegardePartie = new JButton("Savegarde Partie");
        btnSavegardePartie.setBackground(new Color(102, 205, 170));
        btnSavegardePartie.setFont(new Font("Skater Girls Rock", Font.ITALIC, 11));
        btnSavegardePartie.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
  
        		
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(70)
        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
        			.addGap(54)
        			.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
        			.addComponent(btnSavegardePartie)
        			.addGap(48))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(147)
        			.addComponent(lb2)
        			.addContainerGap(214, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(96)
        			.addComponent(icon, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lb2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(icon, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnSavegardePartie)
        				.addComponent(jButton2)
        				.addComponent(jButton1))
        			.addGap(32))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Enregistrement log = new Enregistrement();
        this.dispose();
        
    }  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        this.dispose();
        
    }
 

   
  

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lb2;
    private JLabel icon;
}
